This Lab is based on the Text mining  and NLP Course

## Lab 1.  Data analysis with pandas

# Table of Contents
<ol start="0">
<li> Learning Goals </li>
<li> Loading and Cleaning with Pandas</li>
<li> Parsing and Completing the Dataframe  </li>
<li> Grouping </li>
</ol>

## Learning Goals

About 6000 odd "best books" were fetched and parsed from [Goodreads](https://www.goodreads.com). The "bestness" of these books came from a proprietary formula used by Goodreads and published as a list on their web site.

We parsed the page for each book and saved data from all these pages in a tabular format as a CSV file. In this lab we'll clean and further parse the data.  We'll then do some exploratory data analysis to answer questions about these best books and popular genres.  


By the end of this lab, you should be able to:

- Load and systematically address missing values, for example, by removing observations associated with these values.
- Parse columns in the dataframe to create new dataframe columns.
- Use groupby to aggregate data on a particular feature column, such as author.

Explanation:

Step 1: Loading and Handling Missing Data


When we load the dataset, some information might be missing. These missing values are marked as NaN (Not a Number).
We'll first look at these missing values, and then decide if we should remove those rows or fill in the gaps with something else.

Step 2: Parsing Data Columns


Sometimes, the data we have can be split into more detailed parts. For example, if we have a column that combines an author's full name, we might split it into "First Name" and "Last Name."
This process is called parsing, and it helps us get more specific information from our data.

Step 3: Grouping and Aggregating Data


Grouping data means organizing it based on a shared feature. For example, we can group all books by the same author.
After grouping, we can summarize the data to answer questions like, "Which author has the most books on the list?" or "Which genre is most popular?"

### Basic EDA workflow


The basic workflow is as follows:

1. **Build** a DataFrame from the data (ideally, put all data in this object)
2. **Clean** the DataFrame. It should have the following properties:
    - Each row describes a single object
    - Each column describes a property of that object
    - Columns are numeric whenever appropriate
    - Columns contain atomic properties that cannot be further decomposed
3. Explore **global properties**. Use histograms, scatter plots, and aggregation functions to summarize the data.
4. Explore **group properties**. Use groupby and small multiples to compare subsets of the data.

This process transforms your data into a format which is easier to work with, gives you a basic overview of the data's properties, and likely generates several questions for you to followup in subsequent analysis.

## Part 1: Loading and Cleaning with Pandas
Read in the `goodreads.csv` file, examine the data, and do any necessary data cleaning.

Here is a description of the columns (in order) present in this csv file:

```
rating: the average rating on a 1-5 scale achieved by the book
review_count: the number of Goodreads users who reviewed this book
isbn: the ISBN code for the book
booktype: an internal Goodreads identifier for the book
author_url: the Goodreads (relative) URL for the author of the book
year: the year the book was published
genre_urls: a string with '|' separated relative URLS of Goodreads genre pages
dir: a directory identifier internal to the scraping code
rating_count: the number of ratings for this book (this is different from the number of reviews)
name: the name of the book
```

Let us see what issues we find with the data and resolve them.  



----




After loading appropriate libraries

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)

In [10]:
from google.colab import files

uploaded = files.upload()

Saving goodreads (1).csv to goodreads (1).csv

### Cleaning: Reading in the data
We read in and clean the data from `goodreads.csv`.

In [16]:
import pandas as pd

df = pd.read_csv("/content/goodreads (1).csv")

df.head()

   4.40   136455  0439023483  good_reads:book https://www.goodreads.com/author/show/153394.Suzanne_Collins    2008 /genres/young-adult|/genres/science-fiction|/genres/dystopia|/genres/fantasy|/genres/science-fiction|/genres/romance|/genres/adventure|/genres/book-club|/genres/young-adult|/genres/teen|/genres/apocalyptic|/genres/post-apocalyptic|/genres/action                dir01/2767052-the-hunger-games.html    2958974            The Hunger Games (The Hunger Games, #1)
0  4.41  16648.0  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....            2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...                                                                                                                                                                                                     dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...  1284478.0  Harry Potter and the Order of the Phoenix (Har...
1  3.56  85746.0  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...            2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                                                                                                                                                                                                                             dir01/41865.Twilight.html  2579564.0                            Twilight (Twilight, #1)
2  4.23  47906.0  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...            1960.0  /genres/classics|/genres/fiction|/genres/histo...                                                                                                                                                                                                                 dir01/2657.To_Kill_a_Mockingbird.html  2078123.0                              To Kill a Mockingbird
3  4.23  34772.0  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...            1813.0  /genres/classics|/genres/fiction|/genres/roman...                                                                                                                                                                                                                   dir01/1885.Pride_and_Prejudice.html  1388992.0                                Pride and Prejudice
4  4.25  12363.0  0446675539  good_reads:book  https://www.goodreads.com/author/show/11081.Ma...            1936.0  /genres/classics|/genres/historical-fiction|/g...                                                                                                                                                                                                                   dir01/18405.Gone_with_the_Wind.html   645470.0                                 Gone with the Wind

Oh dear. That does not quite seem to be right. We are missing the column names. We need to add these in! But what are they?

Here is a list of them in order:

`["rating", 'review_count', 'isbn', 'booktype','author_url', 'year', 'genre_urls', 'dir','rating_count', 'name']`

<div class="exercise"><b>Exercise</b></div>
Use these to load the dataframe properly! And then "head" the dataframe... (you will need to look at the read_csv docs)

In [17]:
# your code here
column_names = ["rating", "review_count", "isbn", "booktype", "author_url",
                "year", "genre_urls", "dir", "rating_count", "name"]

df = pd.read_csv("/content/goodreads (1).csv", names=column_names, header=None)
df.head()

   rating  review_count        isbn         booktype                                         author_url    year                                         genre_urls                                                dir  rating_count                                               name
0    4.40      136455.0  0439023483  good_reads:book  https://www.goodreads.com/author/show/153394.S...  2008.0  /genres/young-adult|/genres/science-fiction|/g...                dir01/2767052-the-hunger-games.html     2958974.0            The Hunger Games (The Hunger Games, #1)
1    4.41       16648.0  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....  2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...  dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...     1284478.0  Harry Potter and the Order of the Phoenix (Har...
2    3.56       85746.0  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...  2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                          dir01/41865.Twilight.html     2579564.0                            Twilight (Twilight, #1)
3    4.23       47906.0  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...  1960.0  /genres/classics|/genres/fiction|/genres/histo...              dir01/2657.To_Kill_a_Mockingbird.html     2078123.0                              To Kill a Mockingbird
4    4.23       34772.0  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...  1813.0  /genres/classics|/genres/fiction|/genres/roman...                dir01/1885.Pride_and_Prejudice.html     1388992.0                                Pride and Prejudice

### Cleaning: Examing the dataframe - quick checks

We should examine the dataframe to get a overall sense of the content.

<div class="exercise"><b>Exercise</b></div>
Lets check the types of the columns. What do you find?

In [18]:
# your code here
df.dtypes

rating          float64
review_count    float64
isbn             object
booktype         object
author_url       object
year            float64
genre_urls       object
dir              object
rating_count    float64
name             object
dtype: object

*your answer here*
- These numeric columns (`rating`, `review_count`, `year`, `rating_count`) show up as `float64` instead of `int64` because they contain missing values (`NaN`), and pandas can't store `NaN` in an integer column — so it upcasts the whole column to float. `isbn` is `object` because it's not purely numeric (some ISBN-10 codes end in the letter `X`), so pandas stores it as text.

There are a couple more quick sanity checks to perform on the dataframe.

In [19]:

print(df.shape)
df.columns

(6000, 10)

Index(['rating', 'review_count', 'isbn', 'booktype', 'author_url', 'year', 'genre_urls', 'dir', 'rating_count', 'name'], dtype='object')

### Cleaning: Examining the dataframe - a deeper look

Beyond performing checking some quick general properties of the data frame and looking at the first $n$ rows, we can dig a bit deeper into the values being stored. If you haven't already, check to see if there are any missing values in the data frame.

Let's see for a column which seemed OK to us.

In [20]:
#Get a sense of how many missing values there are in the dataframe. Do it for all columns
np.sum([df.rating.isnull()])

np.int64(2)

In [21]:
#Try to locate where the missing values occur
df[df.rating.isnull()]

      rating  review_count isbn booktype author_url  year genre_urls                              dir  rating_count name
3643     NaN           NaN  NaN      NaN        NaN   NaN        NaN  dir37/9658936-harry-potter.html           NaN  NaN
5282     NaN           NaN  NaN      NaN        NaN   NaN        NaN     dir53/113138.The_Winner.html           NaN  NaN

How does `pandas` or `numpy` handle missing values when we try to compute with data sets that include them?

We'll now check if any of the other suspicious columns have missing values.  Let's look at `year` and `review_count` first.

One thing you can do is to try and convert to the type you expect the column to be. If something goes wrong, it likely means your data are bad.

Lets test for missing data:

In [22]:
df[df.year.isnull()]

      rating  review_count        isbn         booktype                                         author_url  year                                         genre_urls                                                dir  rating_count                                               name
2442    4.23         526.0         NaN  good_reads:book  https://www.goodreads.com/author/show/623606.A...   NaN  /genres/religion|/genres/islam|/genres/non-fic...                       dir25/1301625.La_Tahzan.html        4134.0                                          La Tahzan
2869    4.61           2.0         NaN  good_reads:book  https://www.goodreads.com/author/show/8182217....   NaN                                                NaN  dir29/22031070-my-death-experiences---a-preach...          23.0  My Death Experiences - A Preacherâs 18 Apoca...
3643     NaN           NaN         NaN              NaN                                                NaN   NaN                                                NaN                    dir37/9658936-harry-potter.html           NaN                                                NaN
5282     NaN           NaN         NaN              NaN                                                NaN   NaN                                                NaN                       dir53/113138.The_Winner.html           NaN                                                NaN
5572    3.71          35.0  8423336603  good_reads:book  https://www.goodreads.com/author/show/285658.E...   NaN                                    /genres/fiction  dir56/890680._rase_una_vez_el_amor_pero_tuve_q...         403.0  Ãrase una vez el amor pero tuve que matarlo. ...
5658    4.32          44.0         NaN  good_reads:book  https://www.goodreads.com/author/show/25307.Ro...   NaN  /genres/fantasy|/genres/fantasy|/genres/epic-f...  dir57/5533041-assassin-s-apprentice-royal-assa...        3850.0  Assassin's Apprentice / Royal Assassin (Farsee...
5683    4.56         204.0         NaN  good_reads:book  https://www.goodreads.com/author/show/3097905....   NaN  /genres/fantasy|/genres/young-adult|/genres/ro...                  dir57/12474623-tiger-s-dream.html         895.0                 Tiger's Dream (The Tiger Saga, #5)

### Cleaning: Dealing with Missing Values
How should we interpret 'missing' or 'invalid' values in the data (hint: look at where these values occur)? One approach is to simply exclude them from the dataframe. Is this appropriate for all 'missing' or 'invalid' values?

In [23]:
#Treat the missing or invalid values in your dataframe
#######

df = df[df.year.notnull()]

Ok so we have done some cleaning. What do things look like now? Notice the float has not yet changed.

In [24]:
df.dtypes

rating          float64
review_count    float64
isbn             object
booktype         object
author_url       object
year            float64
genre_urls       object
dir              object
rating_count    float64
name             object
dtype: object

In [25]:
print(np.sum(df.year.isnull()))
print(np.sum(df.rating_count.isnull()))
print(np.sum(df.review_count.isnull()))
# We removed seven rows
df.shape

0
0
0

(5993, 10)

*Suspect observations for rating and rating_count were removed as well! *

<div class="exercise"><b>Exercise</b></div>

Ok so lets fix those types. Convert them to ints. If the type conversion fails, we now know we have further problems.

In [26]:
# your code here

df['year'] = df['year'].astype(int)
df['rating_count'] = df['rating_count'].astype(int)
df['review_count'] = df['review_count'].astype(int)

df.dtypes

rating          float64
review_count      int64
isbn             object
booktype         object
author_url       object
year              int64
genre_urls       object
dir              object
rating_count      int64
name             object
dtype: object

Once you do this, we seem to be good on these columns (no errors in conversion). Lets look:

In [27]:
df.dtypes

rating          float64
review_count      int64
isbn             object
booktype         object
author_url       object
year              int64
genre_urls       object
dir              object
rating_count      int64
name             object
dtype: object

Sweet!

Some of the other colums that should be strings have NaN.

In [28]:
df.loc[df.genre_urls.isnull(), 'genre_urls']=""
df.loc[df.isbn.isnull(), 'isbn']=""

##  Part 2: Parsing and Completing the Data Frame

We will parse the `author` column from the author_url and `genres` column from the genre_urls. Keep the `genres` column as a string separated by '|'.

We will use panda's `map` to assign new columns to the dataframe.

Examine an example `author_url` and reason about which sequence of string operations must be performed in order to isolate the author's name.

In [29]:
#Get the first author_url
test_string = df.author_url[0]
test_string

'https://www.goodreads.com/author/show/153394.Suzanne_Collins'

In [30]:
#Test out some string operations to isolate the author name

test_string.split('/')[-1].split('.')[1:][0]

'Suzanne_Collins'

<div class="exercise"><b>Exercise</b></div>

Lets wrap the above code into a function which we will then use

In [31]:
# Write a function that accepts an author url and returns the author's name based on your experimentation above
def get_author(url):
    # your code here
    author = url.split('/')[-1].split('.')[1:][0]
    return author

In [32]:
#Apply the get_author function to the 'author_url' column using '.map'
#and add a new column 'author' to store the names
df['author'] = df.author_url.map(get_author)
df.author[0:5]

0    Suzanne_Collins
1        J_K_Rowling
2    Stephenie_Meyer
3         Harper_Lee
4        Jane_Austen
Name: author, dtype: object

<div class="exercise"><b>Exercise</b></div>

Now parse out the genres from `genre_url`.  

This is a little more complicated because there be more than one genre.

In [33]:

df.genre_urls.head()

0    /genres/young-adult|/genres/science-fiction|/g...
1    /genres/fantasy|/genres/young-adult|/genres/fi...
2    /genres/young-adult|/genres/fantasy|/genres/ro...
3    /genres/classics|/genres/fiction|/genres/histo...
4    /genres/classics|/genres/fiction|/genres/roman...
Name: genre_urls, dtype: object

In [34]:
# your code here
test_genre_string = df.genre_urls[0]
test_genre_string

#Test out some string operations to isolate the genre name
test_genre_string=df.genre_urls[0]
genres=test_genre_string.strip().split('|')
for e in genres:
    print(e.split('/')[-1])
    "|".join(genres)

young-adult
science-fiction
dystopia
fantasy
science-fiction
romance
adventure
book-club
young-adult
teen
apocalyptic
post-apocalyptic
action

<div class="exercise"><b>Exercise</b></div>

Write a function that accepts a genre url and returns the genre name based on your experimentation above

In [35]:
def split_and_join_genres(url):
    # your code here
    genres = url.strip().split('|')
    genre_names = [g.split('/')[-1] for g in genres]
    return "|".join(genre_names)

Test your function

In [36]:
split_and_join_genres("/genres/young-adult|/genres/science-fiction")

'young-adult|science-fiction'

In [37]:
split_and_join_genres("")

''

<div class="exercise"><b>Exercise</b></div>

Use map again to create a new "genres" column

In [38]:

df['genres']=df.genre_urls.map(split_and_join_genres)
df.head()

   rating  review_count        isbn         booktype                                         author_url  year                                         genre_urls                                                dir  rating_count                                               name           author                                             genres
0    4.40        136455  0439023483  good_reads:book  https://www.goodreads.com/author/show/153394.S...  2008  /genres/young-adult|/genres/science-fiction|/g...                dir01/2767052-the-hunger-games.html       2958974            The Hunger Games (The Hunger Games, #1)  Suzanne_Collins  young-adult|science-fiction|dystopia|fantasy|s...
1    4.41         16648  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....  2003  /genres/fantasy|/genres/young-adult|/genres/fi...  dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...       1284478  Harry Potter and the Order of the Phoenix (Har...      J_K_Rowling  fantasy|young-adult|fiction|fantasy|magic|chil...
2    3.56         85746  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...  2005  /genres/young-adult|/genres/fantasy|/genres/ro...                          dir01/41865.Twilight.html       2579564                            Twilight (Twilight, #1)  Stephenie_Meyer  young-adult|fantasy|romance|paranormal|vampire...
3    4.23         47906  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...  1960  /genres/classics|/genres/fiction|/genres/histo...              dir01/2657.To_Kill_a_Mockingbird.html       2078123                              To Kill a Mockingbird       Harper_Lee  classics|fiction|historical-fiction|academic|s...
4    4.23         34772  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...  1813  /genres/classics|/genres/fiction|/genres/roman...                dir01/1885.Pride_and_Prejudice.html       1388992                                Pride and Prejudice      Jane_Austen  classics|fiction|romance|historical-fiction|li...

Finally, let's pick an author at random so we can see the results of the transformations.  Scroll to see the `author` and `genre` columns that we added to the dataframe.

In [39]:
df[df.author == "Marguerite_Yourcenar"]

      rating  review_count        isbn         booktype                                         author_url  year                                         genre_urls                                  dir  rating_count                name                author                                             genres
1014    4.23           483  0374529264  good_reads:book  https://www.goodreads.com/author/show/7732.Mar...  1951  /genres/historical-fiction|/genres/fiction|/ge...  dir11/12172.Memoirs_of_Hadrian.html          6258  Memoirs of Hadrian  Marguerite_Yourcenar  historical-fiction|fiction|cultural|france|cla...
5620    4.11            74  2070367983  good_reads:book  https://www.goodreads.com/author/show/7732.Mar...  1968  /genres/fiction|/genres/historical-fiction|/ge...     dir57/953435.L_uvre_au_noir.html          1601    L'Åuvre au noir  Marguerite_Yourcenar  fiction|historical-fiction|cultural|france|eur...

Let us delete the `genre_urls` column.

In [40]:
del df['genre_urls']

And then save the dataframe out!

In [41]:
df.to_csv("/content/cleaned-goodreads.csv", index=False, header=True)

---

## Part 3: Grouping

It appears that some books were written in negative years!  Print out the observations that correspond to negative years.  What do you notice about these books?

In [42]:
# your code here
df[df.year < 0]

      rating  review_count        isbn         booktype                                         author_url  year                                                dir  rating_count                                  name        author                                             genres
47      3.68          5785  0143039954  good_reads:book    https://www.goodreads.com/author/show/903.Homer  -800                        dir01/1381.The_Odyssey.html        560248                           The Odyssey         Homer  classics|fiction|poetry|fantasy|mythology|acad...
246     4.01           365  0147712556  good_reads:book    https://www.goodreads.com/author/show/903.Homer  -800              dir03/1375.The_Iliad_The_Odyssey.html         35123                 The Iliad/The Odyssey         Homer  classics|fantasy|mythology|fantasy|academic|sc...
455     3.85          1499  0140449140  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -380                      dir05/30289.The_Republic.html         82022                          The Republic         Plato  philosophy|classics|non-fiction|politics|histo...
596     3.77          1240  0679729526  good_reads:book   https://www.goodreads.com/author/show/919.Virgil   -29                        dir06/12914.The_Aeneid.html         60308                            The Aeneid        Virgil  classics|poetry|fiction|fantasy|mythology|acad...
629     3.64          1231  1580495931  good_reads:book  https://www.goodreads.com/author/show/1002.Sop...  -429                        dir07/1554.Oedipus_Rex.html         93192                           Oedipus Rex     Sophocles  classics|plays|drama|fiction|academic|school|l...
674     3.92          3559  1590302257  good_reads:book  https://www.goodreads.com/author/show/1771.Sun...  -512                    dir07/10534.The_Art_of_War.html        114619                        The Art of War       Sun_Tzu  non-fiction|politics|classics|literature|psych...
746     4.06          1087  0140449183  good_reads:book  https://www.goodreads.com/author/show/5158478....  -500                 dir08/99944.The_Bhagavad_Gita.html         31634                     The Bhagavad Gita     Anonymous  classics|spirituality|religion|hinduism|fantas...
777     3.52          1038  1580493882  good_reads:book  https://www.goodreads.com/author/show/1002.Sop...  -442                           dir08/7728.Antigone.html         49084                              Antigone     Sophocles  drama|fiction|classics|academic|read-for-schoo...
1233    3.94           704  015602764X  good_reads:book  https://www.goodreads.com/author/show/1002.Sop...  -400                  dir13/1540.The_Oedipus_Cycle.html         36008                     The Oedipus Cycle     Sophocles  classics|plays|drama|fiction|literature|academ...
1397    4.03           890  0192840509  good_reads:book  https://www.goodreads.com/author/show/12452.Aesop  -560                    dir14/21348.Aesop_s_Fables.html         71259                        Aesop's Fables         Aesop  classics|childrens|literature|fantasy|fairy-ta...
1398    3.60          1644  0141026286  good_reads:book  https://www.goodreads.com/author/show/5158478.... -1500             dir14/19351.The_Epic_of_Gilgamesh.html         42026                 The Epic of Gilgamesh     Anonymous  religion|literature|ancient|academic|read-for-...
1428    3.80           539  0486275485  good_reads:book  https://www.goodreads.com/author/show/973.Euri...  -431                            dir15/752900.Medea.html         29858                                 Medea     Euripides  classics|plays|drama|fiction|fantasy|mythology...
1815    3.96           493  0140443339  good_reads:book  https://www.goodreads.com/author/show/990.Aesc...  -458                       dir19/1519.The_Oresteia.html         18729                          The Oresteia     Aeschylus  classics|plays|drama|fiction|fantasy|mythology...
1882    4.02           377  0872205541  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -400   dir19/22632.The_Trial_and_Death_of_Socrates.html         18712       The Trial and Death of Socrates         Plato  philosophy|classics|non-fiction|history|litera...
2078    3.84           399  0140440399  good_reads:book  https://www.goodreads.com/author/show/957.Thuc...  -411  dir21/261243.The_History_of_the_Peloponnesian_...         17212  The History of the Peloponnesian War    Thucydides  history|classics|non-fiction|war|war|military|...
2527    3.94           506  0140449086  good_reads:book  https://www.goodreads.com/author/show/901.Hero...  -440                      dir26/1362.The_Histories.html         20570                         The Histories     Herodotus  history|classics|non-fiction|cultural|greece|l...
3133    4.30           131  0872203492  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -400                     dir32/9462.Complete_Works.html          7454                        Complete Works         Plato  philosophy|classics|non-fiction|history|litera...
3274    3.88           411  0140449493  good_reads:book  https://www.goodreads.com/author/show/2192.Ari...  -350            dir33/19068.The_Nicomachean_Ethics.html         16534                The Nicomachean Ethics     Aristotle  philosophy|classics|non-fiction|politics|acade...
3757    3.82           364  0872206033  good_reads:book  https://www.goodreads.com/author/show/1011.Ari...  -411                         dir38/1591.Lysistrata.html         18070                            Lysistrata  Aristophanes  plays|classics|drama|fiction|plays|theatre|hum...
4402    3.99           516  0140449272  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -370                     dir45/81779.The_Symposium.html         18457                         The Symposium         Plato  non-fiction|classics|philosophy|academic|schoo...
4475    4.11           281  0865163480  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -390                           dir45/73945.Apology.html         11478                               Apology         Plato  philosophy|classics|non-fiction|history|academ...
5367    4.07           133  0872206335  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -360                    dir54/30292.Five_Dialogues.html          9964                        Five Dialogues         Plato  philosophy|classics|non-fiction|academic|schoo...

We can determine the "best book" by year! For this we use Pandas groupby. Groupby allows grouping a dataframe by any (usually categorical) variable.

In [43]:
dfgb_author = df.groupby('author')
type(dfgb_author)

pandas.core.groupby.generic.DataFrameGroupBy

Perhaps we want the number of books each author wrote

In [44]:
dfgb_author.count()

                       rating  review_count  isbn  booktype  author_url  year  dir  rating_count  name  genres
author
A_A_Milne                   6             6     6         6           6     6    6             6     6       6
A_G_Howard                  1             1     1         1           1     1    1             1     1       1
A_J_Cronin                  1             1     1         1           1     1    1             1     1       1
A_J_Jacobs                  1             1     1         1           1     1    1             1     1       1
A_J_Salt                    1             1     1         1           1     1    1             1     1       1
...                       ...           ...   ...       ...         ...   ...  ...           ...   ...     ...
_                          42            42    42        42          42    42   42            42    42      42
_gota_Krist_f               1             1     1         1           1     1    1             1     1       1
_mile_Zola                  4             4     4         4           4     4    4             4     4       4
_ric_Emmanuel_Schmitt       1             1     1         1           1     1    1             1     1       1
_sne_Seierstad              1             1     1         1           1     1    1             1     1       1

[2645 rows x 10 columns]

Lots of useless info there. One column should suffice

In [45]:
dfgb_author['author'].count()

author
A_A_Milne                 6
A_G_Howard                1
A_J_Cronin                1
A_J_Jacobs                1
A_J_Salt                  1
                         ..
_                        42
_gota_Krist_f             1
_mile_Zola                4
_ric_Emmanuel_Schmitt     1
_sne_Seierstad            1
Name: author, Length: 2645, dtype: int64

Perhaps you want more detailed info...

In [46]:
dfgb_author[['rating', 'rating_count', 'review_count', 'year']].describe()

                      rating                                                        rating_count                                                                             review_count                                                                      year
                       count      mean       std   min     25%    50%     75%   max        count          mean           std      min       25%      50%       75%       max        count         mean          std     min      25%     50%      75%     max count         mean         std     min      25%     50%      75%     max
author
A_A_Milne                6.0  4.365000  0.078677  4.25  4.3275  4.365  4.4025  4.48          6.0  47842.333333  57135.314010    544.0  15559.50  30547.0  50401.25  157833.0          6.0   543.000000   682.473150     1.0   219.50   309.5   499.25  1886.0   6.0  1944.166667   29.294482  1926.0  1926.25  1927.5  1952.75  1997.0
A_G_Howard               1.0  4.020000       NaN  4.02  4.0200  4.020  4.0200  4.02          1.0  17073.000000           NaN  17073.0  17073.00  17073.0  17073.00   17073.0          1.0  3194.000000          NaN  3194.0  3194.00  3194.0  3194.00  3194.0   1.0  2013.000000         NaN  2013.0  2013.00  2013.0  2013.00  2013.0
A_J_Cronin               1.0  4.220000       NaN  4.22  4.2200  4.220  4.2200  4.22          1.0   1015.000000           NaN   1015.0   1015.00   1015.0   1015.00    1015.0          1.0   109.000000          NaN   109.0   109.00   109.0   109.00   109.0   1.0  1941.000000         NaN  1941.0  1941.00  1941.0  1941.00  1941.0
A_J_Jacobs               1.0  3.750000       NaN  3.75  3.7500  3.750  3.7500  3.75          1.0  39489.000000           NaN  39489.0  39489.00  39489.0  39489.00   39489.0          1.0  4371.000000          NaN  4371.0  4371.00  4371.0  4371.00  4371.0   1.0  2007.000000         NaN  2007.0  2007.00  2007.0  2007.00  2007.0
A_J_Salt                 1.0  4.940000       NaN  4.94  4.9400  4.940  4.9400  4.94          1.0     16.000000           NaN     16.0     16.00     16.0     16.00      16.0          1.0     6.000000          NaN     6.0     6.00     6.0     6.00     6.0   1.0  2014.000000         NaN  2014.0  2014.00  2014.0  2014.00  2014.0
...                      ...       ...       ...   ...     ...    ...     ...   ...          ...           ...           ...      ...       ...      ...       ...       ...          ...          ...          ...     ...      ...     ...      ...     ...   ...          ...         ...     ...      ...     ...      ...     ...
_                       42.0  3.988095  0.301211  3.15  3.8000  4.075  4.2075  4.47         42.0  11574.642857   9368.218450     10.0   4724.00   8709.5  15572.75   39302.0         42.0  1437.214286  1216.421371     1.0   534.75  1020.5  1745.75  4785.0  42.0  1998.904762   18.721071  1941.0  1994.75  2007.0  2010.75  2014.0
_gota_Krist_f            1.0  4.340000       NaN  4.34  4.3400  4.340  4.3400  4.34          1.0   2628.000000           NaN   2628.0   2628.00   2628.0   2628.00    2628.0          1.0   243.000000          NaN   243.0   243.00   243.0   243.00   243.0   1.0  1986.000000         NaN  1986.0  1986.00  1986.0  1986.00  1986.0
_mile_Zola               4.0  3.990000  0.100995  3.84  3.9750  4.035  4.0500  4.05          4.0   8358.250000   4553.226942   3594.0   5181.75   8095.0  11271.50   13649.0          4.0   283.750000   171.069917   125.0   189.50   243.5   337.75   523.0   4.0  1652.500000  456.345264   968.0  1649.75  1878.5  1881.25  1885.0
_ric_Emmanuel_Schmitt    1.0  4.160000       NaN  4.16  4.1600  4.160  4.1600  4.16          1.0   6439.000000           NaN   6439.0   6439.00   6439.0   6439.00    6439.0          1.0   424.000000          NaN   424.0   424.00   424.0   424.00   424.0   1.0  2002.000000         NaN  2002.0  2002.00  2002.0  2002.00  2002.0
_sne_Seierstad           1.0  3.740000       NaN  3.74  3.7400  3.740  3.7400  3.74          1.0  24993.000000           NaN  24993.0  24993.00  24993.0  24993.00   24993.0          1.0  2088.000000          NaN  2088.0  2088.00  2088.0  2088.00  2088.0   1.0  2002.000000         NaN  2002.0  2002.00  2002.0  2002.00  2002.0

[2645 rows x 32 columns]

You can also access a `groupby` dictionary style.

In [47]:
ratingdict = {}
for author, subset in dfgb_author:
    ratingdict[author] = (subset['rating'].mean(), subset['rating'].std())
ratingdict

{'A_A_Milne': (np.float64(4.364999999999999), 0.0786765530510839),
 'A_G_Howard': (np.float64(4.02), nan),
 'A_J_Cronin': (np.float64(4.22), nan),
 'A_J_Jacobs': (np.float64(3.75), nan),
 'A_J_Salt': (np.float64(4.94), nan),
 'A_Meredith_Walters': (np.float64(4.15), 0.16970562748477094),
 'A_N_Roquelaure': (np.float64(3.45), 0.2262741699796951),
 'A_S_Byatt': (np.float64(3.86), nan),
 'A_S_King': (np.float64(3.93), nan),
 'A_id_al_Qarni': (np.float64(4.050000000000001), 0.19798989873223347),
 'Abbi_Glines': (np.float64(4.179285714285713), 0.12916681436834276),
 'Abdul_Rahman_Munif': (np.float64(4.03), nan),
 'Abigail_Gibbs': (np.float64(3.82), nan),
 'Abigail_Roux': (np.float64(4.47), 0.22876479915697992),
 'Abigail_Thomas': (np.float64(3.68), nan),
 'Abolqasem_Ferdowsi': (np.float64(4.52), nan),
 'Abraham_Verghese': (np.float64(4.26), nan),
 'Abul_Hasan_Ali_Nadwi': (np.float64(4.15), nan),
 'Adam_Hochschild': (np.float64(4.14), nan),
 'Adam_Johnson': (np.float64(4.03), nan),
 'Adam_Levin': (np.float64(4.04), nan),
 'Adam_Rex': (np.float64(4.14), nan),
 'Adam_Smith': (np.float64(3.82), nan),
 'Addison_Moore': (np.float64(3.78), nan),
 'Adeline_Yen_Mah': (np.float64(4.01), nan),
 'Adolf_Hitler': (np.float64(2.97), nan),
 'Adolfo_Bioy_Casares': (np.float64(4.06), nan),
 'Aeschylus': (np.float64(3.96), nan),
 'Aesop': (np.float64(4.03), nan),
 'Agatha_Christie': (np.float64(3.9772727272727266), 0.12190905701307918),
 'Ahlam_Mosteghanemi': (np.float64(3.97), nan),
 'Ahmad_Baari': (np.float64(4.88), nan),
 'Ahmad_Fuadi': (np.float64(4.0), nan),
 'Ai_Yazawa': (np.float64(4.19), nan),
 'Aidan_Chambers': (np.float64(4.27), nan),
 'Aimee_Carter': (np.float64(3.9133333333333336), 0.13051181300301234),
 'Aimee_Friedman': (np.float64(3.64), nan),
 'Alain_Fournier': (np.float64(3.79), nan),
 'Alan_Bradley': (np.float64(3.79), nan),
 'Alan_Brennert': (np.float64(4.13), nan),
 'Alan_Campbell': (np.float64(3.58), nan),
 'Alan_Hollinghurst': (np.float64(3.65), nan),
 'Alan_Lightman': (np.float64(4.07), nan),
 'Alan_Moore': (np.float64(4.198), 0.1630030674557996),
 'Alan_Paton': (np.float64(3.83), nan),
 'Alan_Wilson_Watts': (np.float64(4.27), nan),
 'Alastair_Reynolds': (np.float64(4.09), nan),
 'Albert_Camus': (np.float64(4.032000000000001), 0.09523654760647308),
 'Albert_Einstein': (np.float64(4.13), nan),
 'Albert_Espinosa': (np.float64(3.36), nan),
 'Alcoholics_Anonymous': (np.float64(4.39), nan),
 'Aldo_Leopold': (np.float64(4.22), nan),
 'Aldous_Huxley': (np.float64(3.9400000000000004), 0.12288205727444491),
 'Aleatha_Romig': (np.float64(4.275), 0.27577164466275333),
 'Alecia_Stone': (np.float64(4.455), 0.657609306503489),
 'Aleksandr_Solzhenitsyn': (np.float64(4.0600000000000005),
  0.12288205727444532),
 'Alessandro_Baricco': (np.float64(4.036666666666666), 0.21361959960016158),
 'Alessandro_Manzoni': (np.float64(3.71), nan),
 'Alex_Flinn': (np.float64(3.8200000000000003), 0.04242640687119289),
 'Alex_Garland': (np.float64(3.5300000000000002), 0.46669047558312116),
 'Alex_Haley': (np.float64(4.39), nan),
 'Alex_Harris': (np.float64(4.11), nan),
 'Alex_Kotlowitz': (np.float64(4.23), nan),
 'Alex_Sanchez': (np.float64(3.91), 0.08485281374238578),
 'Alexander_Gordon_Smith': (np.float64(4.09), nan),
 'Alexander_Jovy': (np.float64(4.12), nan),
 'Alexander_McCall_Smith': (np.float64(3.7), nan),
 'Alexander_Pushkin': (np.float64(4.03), nan),
 'Alexandra_Adornetto': (np.float64(3.8666666666666667), 0.16441816606851367),
 'Alexandra_Bracken': (np.float64(4.2), 0.3269556544854364),
 'Alexandra_Fuller': (np.float64(3.94), nan),
 'Alexandra_Ivy': (np.float64(3.9899999999999998), 0.21213203435596414),
 'Alexandra_Monir': (np.float64(3.88), nan),
 'Alexandra_Potter': (np.float64(3.18), nan),
 'Alexandra_Ripley': (np.float64(3.23), nan),
 'Alexandre_Dumas': (np.float64(4.09), 0.08485281374238578),
 'Alexandre_Dumas_fils': (np.float64(3.94), nan),
 'Alexei_Maxim_Russell': (np.float64(4.17), 0.6298412498399895),
 'Alexis_de_Tocqueville': (np.float64(3.94), nan),
 'Alfred_Bester': (np.float64(4.075), 0.10606601717798238),
 'Alfred_Lansing': (np.float64(4.31), nan),
 'Alfred_Tennyson': (np.float64(4.04), nan),
 'Ali_Marsman': (np.float64(4.1), nan),
 'Ali_Smith': (np.float64(3.46), nan),
 'Alice_Clayton': (np.float64(4.19), nan),
 'Alice_Hoffman': (np.float64(3.7942857142857145), 0.11602544876838351),
 'Alice_Kuipers': (np.float64(3.65), nan),
 'Alice_Schroeder': (np.float64(4.03), nan),
 'Alice_Sebold': (np.float64(3.725), 0.007071067811865324),
 'Alice_Walker': (np.float64(4.074999999999999), 0.07778174593052045),
 'Alija_Izetbegovi_': (np.float64(4.46), nan),
 'Alison_Bechdel': (np.float64(4.12), nan),
 'Alison_Croggon': (np.float64(4.2175), 0.2766917659297678),
 'Alison_Goodman': (np.float64(4.0649999999999995), 0.0919238815542511),
 'Alison_Weir': (np.float64(3.9899999999999998), 0.08888194417315584),
 'Alistair_MacLeod': (np.float64(3.98), nan),
 'Allan_Frewin_Jones': (np.float64(3.795), 0.28991378028648457),
 'Allan_Gurganus': (np.float64(3.83), nan),
 'Allan_Pease': (np.float64(3.94), nan),
 'Allegra_Goodman': (np.float64(3.67), nan),
 'Allen_Ginsberg': (np.float64(4.15), nan),
 'Ally_Carter': (np.float64(4.197777777777778), 0.21194207804125262),
 'Ally_Condie': (np.float64(3.6133333333333333), 0.1040832999733067),
 'Ally_Shields': (np.float64(3.83), nan),
 'Allyse_Near': (np.float64(4.26), nan),
 'Alma_Katsu': (np.float64(3.69), nan),
 'Alyson_Noel': (np.float64(3.772), 0.17516975893242662),
 'Alyxandra_Harvey': (np.float64(4.03), 0.1153256259467082),
 'Am_lie_Nothomb': (np.float64(3.77), 0.08485281374238578),
 'Amanda_E_Alvarez': (np.float64(3.77), nan),
 'Amanda_Hocking': (np.float64(3.95375), 0.12993817211054096),
 'Amber_Argyle': (np.float64(3.69), nan),
 'Amber_Lea_Easton': (np.float64(4.21), nan),
 'Ambrose_Bierce': (np.float64(4.15), nan),
 'Amelia_Atwater_Rhodes': (np.float64(4.041666666666667), 0.13090709173557669),
 'Amelia_Hutchins': (np.float64(4.38), 0.19798989873223286),
 'Ami_McKay': (np.float64(3.97), nan),
 'Amin_Maalouf': (np.float64(4.17), nan),
 'Amish_Tripathi': (np.float64(3.93), 0.0),
 'Amitav_Ghosh': (np.float64(3.91), nan),
 'Amor_Towles': (np.float64(3.98), nan),
 'Amy_A_Bartol': (np.float64(4.3375), 0.16680827317612265),
 'Amy_Efaw': (np.float64(3.72), nan),
 'Amy_Harmon': (np.float64(4.365), 0.14849242404917495),
 'Amy_Hempel': (np.float64(4.27), nan),
 'Amy_Plum': (np.float64(4.105), 0.12020815280171367),
 'Amy_Tan': (np.float64(3.8200000000000003), 0.24361855430159662),
 'Anastacia_Moore': (np.float64(4.65), nan),
 'Anchee_Min': (np.float64(3.86), nan),
 'Andr_Aciman': (np.float64(4.04), nan),
 'Andr_Gide': (np.float64(3.67), nan),
 'Andre_Agassi': (np.float64(4.11), nan),
 'Andre_Dubus_III': (np.float64(3.77), nan),
 'Andrea_Cremer': (np.float64(4.066666666666666), 0.055075705472860864),
 'Andrea_Hirata': (np.float64(3.94), 0.2764054992217052),
 'Andrea_Levy': (np.float64(3.86), nan),
 'Andrew_Clements': (np.float64(3.8266666666666667), 0.05859465277082333),
 'Andrew_Davidson': (np.float64(3.96), nan),
 'Andrew_Klavan': (np.float64(4.12), 0.1838477631085022),
 'Andrew_Smith': (np.float64(4.17), nan),
 'Andrzej_Sapkowski': (np.float64(4.273333333333333), 0.11060440015358027),
 'Andy_Szpuk': (np.float64(4.18), nan),
 'Andy_Weir': (np.float64(4.33), nan),
 'Angel_Sefer': (np.float64(4.43), nan),
 'Angela_Carter': (np.float64(4.01), 0.0707106781186545),
 'Angela_Morrison': (np.float64(4.0), nan),
 'Angelo_Tsanatelis': (np.float64(4.1899999999999995), 0.21213203435596412),
 'Angie_Martin': (np.float64(4.4399999999999995), 0.11313708498984708),
 'Angie_Sage': (np.float64(3.865), 0.134350288425444),
 'Anita_Diamant': (np.float64(4.13), nan),
 'Anita_Shreve': (np.float64(3.84), nan),
 'Ann_Aguirre': (np.float64(4.025), 0.14849242404917495),
 'Ann_Brashares': (np.float64(3.742857142857143), 0.10291003930849597),
 'Ann_Fairbairn': (np.float64(4.41), nan),
 'Ann_M_Martin': (np.float64(4.16), nan),
 'Ann_Marie_MacDonald': (np.float64(3.91), nan),
 'Ann_Patchett': (np.float64(3.78), 0.1513274595042156),
 'Ann_Rule': (np.float64(4.029999999999999), 0.12186057606953923),
 'Anna_Banks': (np.float64(4.0600000000000005), 0.014142135623731277),
 'Anna_Carey': (np.float64(3.8200000000000003), 0.1555634918610406),
 'Anna_Gavalda': (np.float64(4.1), nan),
 'Anna_Godbersen': (np.float64(3.7866666666666666), 0.12701705922171752),
 'Anna_Lee_Waldo': (np.float64(4.2), nan),
 'Anna_Quindlen': (np.float64(3.81), nan),
 'Anna_Sewell': (np.float64(3.92), nan),
 'Anne_Bishop': (np.float64(4.253), 0.14735067771212387),
 'Anne_Bront_': (np.float64(3.7249999999999996), 0.19091883092036785),
 'Anne_Carson': (np.float64(4.39), nan),
 'Anne_Elisabeth_Stengl': (np.float64(4.18), 0.39509492530276813),
 'Anne_Fadiman': (np.float64(4.12), nan),
 'Anne_Fortier': (np.float64(3.9), nan),
 'Anne_Frank': (np.float64(4.06), nan),
 'Anne_Lamott': (np.float64(4.18), 0.042426406871192576),
 'Anne_McCaffrey': (np.float64(4.033076923076924), 0.1835022531825615),
 'Anne_Michaels': (np.float64(3.96), nan),
 'Anne_Morrow_Lindbergh': (np.float64(4.18), nan),
 'Anne_Rice': (np.float64(3.812105263157895), 0.14401307607947048),
 'Anne_Tyler': (np.float64(3.8316666666666666), 0.16702295251451718),
 'Annemarie_Selinko': (np.float64(3.94), nan),
 'Annette_Curtis_Klause': (np.float64(3.7), 0.09899494936611673),
 'Annie_Dillard': (np.float64(3.98), 0.19798989873223347),
 'Annie_Proulx': (np.float64(3.8449999999999998), 0.10606601717798206),
 'Anonymous': (np.float64(4.265294117647059), 0.3613363676524068),
 'Anthony_Bourdain': (np.float64(3.97), nan),
 'Anthony_Burgess': (np.float64(4.055), 0.14849242404917495),
 'Anthony_Doerr': (np.float64(4.19), nan),
 'Anthony_Hope': (np.float64(3.87), nan),
 'Anthony_Horowitz': (np.float64(4.0672727272727265), 0.08462752614733685),
 'Anthony_Kiedis': (np.float64(4.06), nan),
 'Anthony_Marra': (np.float64(4.15), nan),
 'Anthony_Ryan': (np.float64(4.54), nan),
 'Anthony_Swofford': (np.float64(3.59), nan),
 'Anthony_Trollope': (np.float64(4.01), 0.028284271247461926),
 'Antoine_de_Saint_Exup_ry': (np.float64(4.293333333333333),
  0.1365039681962884),
 'Anton_Chekhov': (np.float64(4.06), 0.35791060336346536),
 'Antonia_Fraser': (np.float64(3.89), nan),
 'Antonia_Michaelis': (np.float64(4.14), nan),
 'Antony_Beevor': (np.float64(4.28), nan),
 'Anya_Seton': (np.float64(4.18), nan),
 'Aporva_Kala': (np.float64(4.355), 0.10606601717798175),
 'April_Henry': (np.float64(3.94), nan),
 'Aprilynne_Pike': (np.float64(4.0225), 0.19720970226301415),
 'Aravind_Adiga': (np.float64(3.69), nan),
 'Ariana_Franklin': (np.float64(3.94), nan),
 'Aristophanes': (np.float64(3.82), nan),
 'Aristotle': (np.float64(3.88), nan),
 'Arkady_Strugatsky': (np.float64(4.275), 0.06363961030678918),
 'Armando_Cosani': (np.float64(4.55), nan),
 'Armistead_Maupin': (np.float64(4.07), nan),
 'Art_Spiegelman': (np.float64(4.426666666666667), 0.07767453465154048),
 'Arthur_C_Clarke': (np.float64(3.9659999999999997), 0.17285832349065502),
 'Arthur_Conan_Doyle': (np.float64(4.198461538461538), 0.2004098364953741),
 'Arthur_Golden': (np.float64(4.03), nan),
 'Arthur_Koestler': (np.float64(4.03), nan),
 'Arthur_Miller': (np.float64(3.47), 0.028284271247461926),
 'Arthur_Ransome': (np.float64(3.97), nan),
 'Arthur_Rimbaud': (np.float64(4.3933333333333335), 0.0461880215351701),
 'Arthur_Schnitzler': (np.float64(3.79), nan),
 'Arturo_P_rez_Reverte': (np.float64(3.8049999999999997),
  0.007071067811865638),
 'Arun_Tiwari': (np.float64(4.1), nan),
 'Arundhati_Roy': (np.float64(3.88), nan),
 'Asa_Don_Brown': (np.float64(4.45), nan),
 'Ashley_Chappell': (np.float64(4.605), 0.26162950903902266),
 'Ashley_Waelti': (np.float64(4.36), nan),
 'Astrid_Lindgren': (np.float64(4.1899999999999995), 0.12000000000000009),
 'Audrey_Niffenegger': (np.float64(3.565), 0.5020458146424487),
 'Augusten_Burroughs': (np.float64(3.815), 0.23334523779156074),
 'Augustine_of_Hippo': (np.float64(3.82), nan),
 'Aurora_Rose_Reynolds': (np.float64(4.21), nan),
 'Austin_Kleon': (np.float64(3.88), nan),
 'Author_Neva_Squires_Rodriguez': (np.float64(4.25), nan),
 'Autumn_Cornwell': (np.float64(3.95), nan),
 'Avery_Aster': (np.float64(3.73), 0.3144307024873154),
 'Avi': (np.float64(3.79), nan),
 'Ayaan_Hirsi_Ali': (np.float64(4.18), nan),
 'Ayn_Rand': (np.float64(3.7979999999999996), 0.1739827577663947),
 'Azar_Nafisi': (np.float64(3.54), nan),
 'B_Kristin_McMichael': (np.float64(3.8700000000000006), 0.14106735979665874),
 'Banana_Yoshimoto': (np.float64(3.82), nan),
 'Barack_Obama': (np.float64(3.66), nan),
 'Barbara_Demick': (np.float64(4.41), nan),
 'Barbara_Ehrenreich': (np.float64(3.58), nan),
 'Barbara_Erskine': (np.float64(4.04), nan),
 'Barbara_Kingsolver': (np.float64(3.931666666666666), 0.11321071798494443),
 'Barbara_Taylor_Bradford': (np.float64(4.12), nan),
 'Barbara_W_Tuchman': (np.float64(4.126666666666666), 0.08082903768654764),
 'Barry_Jordan_Jr_': (np.float64(4.48), nan),
 'Barry_Lyga': (np.float64(3.99), nan),
 'Barry_Unsworth': (np.float64(4.12), nan),
 'Beatrice_Sparks': (np.float64(3.76), nan),
 'Beatrix_Potter': (np.float64(4.24), 0.14142135623730964),
 'Becca_Fitzpatrick': (np.float64(4.24), 0.18264720090929407),
 'Belle_Aurora': (np.float64(4.255), 0.12020815280171303),
 'Belsebuub': (np.float64(4.62), nan),
 'Belzebuub': (np.float64(4.475), 0.0919238815542511),
 'Ben_Goldacre': (np.float64(4.07), nan),
 'Ben_Peller': (np.float64(4.18), 0.21213203435596412),
 'Ben_Sherwood': (np.float64(3.99), nan),
 'Benedict_Freedman': (np.float64(4.12), nan),
 'Benjamin_Alire_S_enz': (np.float64(4.27), nan),
 'Benjamin_Franklin': (np.float64(3.78), nan),
 'Benjamin_Graham': (np.float64(4.24), nan),
 'Benjamin_Hoff': (np.float64(4.0600000000000005), 0.08485281374238578),
 'Bernadette_Azizi': (np.float64(4.06), nan),
 'Bernard_Cornwell': (np.float64(4.123333333333333), 0.22327113561766107),
 'Bernard_Malamud': (np.float64(3.77), 0.2262741699796954),
 'Bernhard_Schlink': (np.float64(3.69), nan),
 'Bertolt_Brecht': (np.float64(3.66), nan),
 'Bertrand_Russell': (np.float64(4.02), nan),
 'Beryl_Markham': (np.float64(4.18), nan),
 'Bess_Streeter_Aldrich': (np.float64(4.07), nan),
 'Beth_Fantaskey': (np.float64(3.86), nan),
 'Beth_Hoffman': (np.float64(3.89), nan),
 'Beth_Revis': (np.float64(3.94), 0.19798989873223347),
 'Bethany_Hamilton': (np.float64(4.12), nan),
 'Bette_Greene': (np.float64(3.63), nan),
 'Betty_Edwards': (np.float64(3.86), nan),
 'Betty_Friedan': (np.float64(3.81), nan),
 'Betty_MacDonald': (np.float64(4.15), nan),
 'Betty_Mahmoody': (np.float64(3.99), nan),
 'Betty_Smith': (np.float64(4.22), nan),
 'Bev_Stout': (np.float64(4.4), nan),
 'Bill_Bryson': (np.float64(3.963333333333333), 0.10535653752852739),
 'Bill_Courtney': (np.float64(4.39), nan),
 'Bill_Konigsberg': (np.float64(4.05), nan),
 'Bill_Martin_Jr_': (np.float64(4.16), nan),
 'Bill_Watterson': (np.float64(4.690000000000001), 0.060415229867972826),
 'Billie_Letts': (np.float64(3.97), nan),
 'Bisco_Hatori': (np.float64(4.35), nan),
 'Blue_Jeans': (np.float64(4.15), nan),
 'Bo_Hampton': (np.float64(3.94), nan),
 'Bob_Atkinson': (np.float64(4.15), nan),
 'Bob_Dylan': (np.float64(3.99), nan),
 'Bodie_Thoene': (np.float64(4.336666666666666), 0.06806859285554051),
 'Bohumil_Hrabal': (np.float64(4.16), 0.05656854249492385),
 'Boris_Pasternak': (np.float64(4.02), nan),
 'Boris_Vian': (np.float64(4.035), 0.0212132034355966),
 'Brae_Wyckoff': (np.float64(3.92), nan),
 'Bram_Stoker': (np.float64(3.94), nan),
 'Brandon_Mull': (np.float64(4.211666666666666), 0.15419684389333865),
 'Brandon_Sanderson': (np.float64(4.316363636363636), 0.2578089497000725),
 'Bree_Despain': (np.float64(3.945), 0.1626345596729056),
 'Brenna_Yovanoff': (np.float64(3.58), nan),
 'Brent_Weeks': (np.float64(4.300000000000001), 0.11882760622010352),
 'Bret_Easton_Ellis': (np.float64(3.62), 0.13656500283747663),
 'Brett_Axel': (np.float64(4.61), nan),
 'Brian_Celio': (np.float64(4.05), nan),
 'Brian_Greene': (np.float64(4.1), nan),
 'Brian_Jacques': (np.float64(4.009285714285714), 0.07205385653633149),
 'Brian_K_Vaughan': (np.float64(4.15), nan),
 'Brian_Katcher': (np.float64(3.89), nan),
 'Brian_L_Weiss': (np.float64(4.16), nan),
 'Brian_Lumley': (np.float64(3.96), nan),
 'Brian_Patrick_McKinley': (np.float64(4.53), nan),
 'Brian_Selznick': (np.float64(4.175), 0.06363961030678918),
 'Brigid_Kemmerer': (np.float64(4.125), 0.1484924240491756),
 'Brodi_Ashton': (np.float64(3.81), nan),
 'Brom': (np.float64(4.09), nan),
 'Brother_Andrew': (np.float64(4.29), nan),
 'Brother_Lawrence': (np.float64(4.31), nan),
 'Bruce_Campbell': (np.float64(4.01), nan),
 'Bruno_Schulz': (np.float64(4.2), nan),
 'Bryan_Davis': (np.float64(4.17), nan),
 'Bryan_Lee_O_Malley': (np.float64(4.24), 0.09899494936611643),
 'Bryce_Courtenay': (np.float64(4.125), 0.15631165450257803),
 'CLAMP': (np.float64(4.12), nan),
 'C_C_Humphreys': (np.float64(3.82), nan),
 'C_C_Hunter': (np.float64(4.322), 0.10183319694480758),
 'C_D_Payne': (np.float64(4.03), nan),
 'C_E_Kilgore': (np.float64(3.96), nan),
 'C_G_Jung': (np.float64(4.18), nan),
 'C_J_Box': (np.float64(3.8), nan),
 'C_J_Daugherty': (np.float64(4.105), 0.1343502884254443),
 'C_J_Redwine': (np.float64(3.74), nan),
 'C_J_Roberts': (np.float64(4.27), 0.1664331697709322),
 'C_J_Sansom': (np.float64(4.06), nan),
 'C_L_Stone': (np.float64(4.416666666666667), 0.10969655114602912),
 'C_L_Wilson': (np.float64(4.239999999999999), 0.13076696830622028),
 'C_S_Lewis': (np.float64(4.056111111111111), 0.13856996062252486),
 'Caleb_Carr': (np.float64(4.03), nan),
 'Candace_Bushnell': (np.float64(3.56), nan),
 'Candice_Millard': (np.float64(4.17), nan),
 'Cao_Xueqin': (np.float64(4.05), nan),
 'Cara_Lynn_Shultz': (np.float64(3.91), nan),
 'Caragh_M_O_Brien': (np.float64(3.92), nan),
 'Carl_Hiaasen': (np.float64(3.8099999999999996), 0.04242640687119289),
 'Carl_Sagan': (np.float64(4.26), 0.12549900398011124),
 'Carla_Capshaw': (np.float64(4.29), 0.03605551275463999),
 'Carlo_Collodi': (np.float64(3.83), nan),
 'Carlos_Castaneda': (np.float64(3.91), nan),
 'Carlos_Rivera': (np.float64(4.53), nan),
 'Carlos_Ruiz_Zaf_n': (np.float64(3.89), 0.25910100990411694),
 'Carol_E_Wyer': (np.float64(4.25), nan),
 'Carol_Plum_Ucci': (np.float64(4.06), nan),
 'Carol_Rifka_Brunt': (np.float64(4.04), nan),
 'Carol_Shields': (np.float64(3.79), nan),
 'Carole_Wilkinson': (np.float64(3.94), nan),
 'Carolina_Andujar': (np.float64(4.32), nan),
 'Caroline_B_Cooney': (np.float64(3.7), nan),
 'Carolyn_Jessop': (np.float64(3.94), nan),
 'Carolyn_Keene': (np.float64(3.935), 0.0212132034355966),
 'Carolyn_Turgeon': (np.float64(3.6), nan),
 'Carrie_Jones': (np.float64(3.9033333333333338), 0.16502525059315412),
 'Carrie_Ryan': (np.float64(3.8633333333333333), 0.22744962812309308),
 'Carrie_Vaughn': (np.float64(3.66), nan),
 'Carson_McCullers': (np.float64(3.9133333333333336), 0.11239810200058233),
 'Cassandra_Clare': (np.float64(4.428461538461539), 0.18876114332872967),
 'Cat_Clarke': (np.float64(3.85), 0.1131370849898477),
 'Cat_Patrick': (np.float64(3.825), 0.007071067811865638),
 'Cate_Tiernan': (np.float64(4.085), 0.07778174593051983),
 'Cath_Crowley': (np.float64(3.89), nan),
 'Catherine_Anderson': (np.float64(4.21), 0.05873670062235346),
 'Catherine_Fisher': (np.float64(3.67), 0.04242640687119289),
 'Catherine_Gilbert_Murdock': (np.float64(3.72), nan),
 'Catherine_Hardwicke': (np.float64(4.13), nan),
 'Catherine_Jinks': (np.float64(3.79), nan),
 'Catherine_Marshall': (np.float64(4.16), nan),
 'Catherynne_M_Valente': (np.float64(4.096666666666667), 0.09451631252505201),
 'Cecelia_Ahern': (np.float64(3.85), 0.12708265027138832),
 'Cecily_von_Ziegesar': (np.float64(3.6233333333333335), 0.13613718571108077),
 'Celia_Rees': (np.float64(3.82), nan),
 'Celso_Cukierkorn': (np.float64(4.15), nan),
 'Chad_Harbach': (np.float64(3.99), nan),
 'Chaim_Potok': (np.float64(4.05), 0.10099504938362074),
 'Chanda_Hahn': (np.float64(3.995), 0.16263455967290624),

<div class="exercise"><b>Exercise</b></div>

Lets get the best-rated book(s) for every year in our dataframe.

In [48]:
#Using .groupby, we can divide the dataframe into subsets by the values of 'year'.
#We can then iterate over these subsets
# your code here
for year, subset in df.groupby('year'):
    best = subset.loc[subset['rating'].idxmax()]
    print(year, '-', best['name'], '(', best['rating'], ')')

-1500 - The Epic of Gilgamesh ( 3.6 )
-800 - The Iliad/The Odyssey ( 4.01 )
-560 - Aesop's Fables ( 4.03 )
-512 - The Art of War ( 3.92 )
-500 - The Bhagavad Gita ( 4.06 )
-458 - The Oresteia ( 3.96 )
-442 - Antigone ( 3.52 )
-440 - The Histories ( 3.94 )
-431 - Medea ( 3.8 )
-429 - Oedipus Rex ( 3.64 )
-411 - The History of the Peloponnesian War ( 3.84 )
-400 - Complete Works ( 4.3 )
-390 - Apology ( 4.11 )
-380 - The Republic ( 3.85 )
-370 - The Symposium ( 3.99 )
-360 - Five Dialogues ( 4.07 )
-350 - The Nicomachean Ethics ( 3.88 )
-29 - The Aeneid ( 3.77 )
4 - The Seven Spiritual Laws of Success ( 4.04 )
8 - Metamorphoses ( 4.01 )
13 - The Day Jesus Rode Into Croydon ( 3.85 )
100 - The New Oxford Annotated Bible, New Revised Standard Version ( 4.3 )
121 - The Twelve Caesars ( 4.02 )
130 - Holy Bible ( 4.45 )
158 - The Golden Ass ( 3.88 )
174 - Meditations ( 4.16 )
200 - The Garden of Eden ( 3.75 )
201 - Fe Fi FOE Comes ( 4.37 )
213 - NaÃ¯ve. Super ( 3.9 )
397 - Confessions ( 3.82 )
632 - The Quran ( 4.37 )
800 - Beowulf ( 3.38 )
900 - The Arabian Nights ( 4.04 )
968 - La BÃªte humaine (Les Rougon-Macquart, #17) ( 4.02 )
1002 - The Pillow Book ( 4.04 )
1008 - The Tale of Genji ( 3.68 )
1010 - Shahnameh ( 4.52 )
1100 - Rubaiyat of Omar Khayyam ( 4.22 )
1106 - The TÃ¡in ( 3.98 )
1140 - Poema de MÃ­o Cid ( 3.42 )
1200 - The Poetic Edda ( 4.24 )
1215 - ÙØ«ÙÙÛ ÙØ¹ÙÙÛ ( 4.44 )
1220 - The Prose Edda ( 4.16 )
1300 - The Imitation of Christ ( 4.16 )
1314 - Inferno (The Divine Comedy, #1) ( 3.96 )
1321 - The Divine Comedy ( 4.04 )
1348 - The Decameron ( 3.85 )
1386 - Auto-da-FÃ© ( 4.04 )
1390 - Sir Gawain and the Green Knight ( 3.66 )
1391 - Keep the Aspidistra Flying ( 3.86 )
1485 - Le Morte d'Arthur ( 3.91 )
1516 - Utopia ( 3.46 )
1522 - Three Kingdoms ( 4.41 )
1532 - The Prince ( 3.72 )
1572 - The Complete Essays ( 4.21 )
1589 - Titus Andronicus ( 3.7 )
1590 - The Taming of the Shrew ( 3.82 )
1592 - Monkey ( 4.04 )
1595 - A Midsummer Night's Dream ( 3.93 )
1597 - Richard III ( 3.9 )
1599 - Much Ado About Nothing ( 4.05 )
1600 - Henry V ( 3.85 )
1601 - Twelfth Night ( 3.95 )
1602 - Hamlet ( 3.98 )
1603 - Othello ( 3.86 )
1604 - Doctor Faustus ( 3.77 )
1605 - King Lear ( 3.88 )
1606 - Antony and Cleopatra ( 3.64 )
1608 - Coriolanus ( 3.65 )
1609 - Shakespeare's Sonnets ( 4.24 )
1611 - Holy Bible ( 4.39 )
1621 - The Anatomy of Melancholy ( 4.21 )
1623 - The Complete Works ( 4.5 )
1635 - La vida es sueÃ±o ( 3.98 )
1642 - A Book of Five Rings ( 4.11 )
1667 - Paradise Lost ( 3.77 )
1678 - The Pilgrim's Progress ( 3.92 )
1680 - The Divan ( 4.65 )
1691 - The Practice of the Presence of God ( 4.31 )
1719 - Robinson Crusoe ( 3.62 )
1721 - Moll Flanders ( 3.45 )
1726 - Gulliver's Travels ( 3.52 )
1729 - A Modest Proposal and Other Satirical Works ( 4.03 )
1748 - Clarissa, or, the History of a Young Lady ( 3.28 )
1749 - The History of Tom Jones, a Foundling ( 3.72 )
1759 - Candide ( 3.74 )
1767 - The Life and Opinions of Tristram Shandy, Gentleman ( 3.76 )
1774 - The Sorrows of Young Werther ( 3.59 )
1776 - The Declaration of Independence and The Constitution of the United States ( 4.44 )
1778 - Evelina ( 3.62 )
1781 - Critique of Pure Reason ( 3.85 )
1782 - Les Liaisons Dangereuses ( 4.08 )
1787 - The Constitution of the United States of America ( 4.52 )
1790 - The Marriage of Heaven and Hell ( 4.27 )
1791 - Dream of the Red Chamber ( 4.05 )
1794 - Songs of Innocence and of Experience ( 4.11 )
1795 - The Monk ( 3.77 )
1798 - Lyrical Ballads ( 3.92 )
1806 - Phenomenology of Spirit ( 3.85 )
1811 - Sense and Sensibility ( 4.04 )
1812 - The Complete Grimm's Fairy Tales ( 4.29 )
1813 - Pride and Prejudice ( 4.23 )
1814 - Mansfield Park ( 3.79 )
1815 - Emma ( 3.97 )
1817 - Persuasion ( 4.12 )
1818 - Frankenstein ( 3.7 )
1819 - Ivanhoe ( 3.71 )
1820 - The Legend of Sleepy Hollow ( 3.94 )
1823 - The Night Before Christmas ( 4.34 )
1824 - Don Juan ( 3.79 )
1825 - Eugene Onegin ( 4.03 )
1826 - The Last of the Mohicans (The Leatherstocking Tales #2) ( 3.67 )
1830 - The Book of Mormon ( 4.42 )
1831 - The Hunchback of Notre-Dame ( 3.93 )
1832 - Faust ( 3.98 )
1833 - Poetry ( 4.04 )
1834 - PÃ¨re Goriot ( 3.79 )
1835 - Hymns of The Church of Jesus Christ of Latter-day Saints ( 4.68 )
1837 - A Season in Hell/The Drunken Boat ( 4.34 )
1839 - A Hero of Our Time ( 4.09 )
1840 - Tales of Mystery and Imagination ( 4.2 )
1841 - The Old Curiosity Shop ( 3.69 )
1842 - The pit and the pendulum and other stories (Penguin 60s) ( 4.12 )
1843 - Lost Illusions ( 4.14 )
1844 - The Raven ( 4.23 )
1845 - The Raven and Other Poems ( 4.27 )
1847 - Jane Eyre ( 4.07 )
1848 - White Nights and Other Stories ( 4.09 )
1849 - The Law ( 4.4 )
1850 - Ishmael ( 4.4 )
1851 - Paris Spleen ( 4.33 )
1852 - Uncle Tom's Cabin ( 3.77 )
1853 - The History of Joseph Smith by His Mother ( 4.37 )
1854 - Walden & Civil Disobedience ( 3.97 )
1855 - North and South ( 4.13 )
1856 - Song of Myself ( 4.17 )
1857 - Les Fleurs du Mal ( 4.26 )
1859 - The Origin of Species ( 3.94 )
1860 - Stepping Heavenward ( 4.27 )
1861 - Notes from Underground ( 4.14 )
1862 - Les MisÃ©rables ( 4.09 )
1863 - From the Earth to the Moon (Extraordinary Voyages, #4) ( 3.76 )
1864 - Our Mutual Friend ( 4.08 )
1865 - Alice's Adventures in Wonderland & Through the Looking-Glass ( 4.05 )
1866 - Morning and Evening, Based on the English Standard Version ( 4.49 )
1867 - Capital, Volume 1 (Das Kapital, #1) ( 4.15 )
1868 - Little Women (Little Women, #1) ( 4.0 )
1869 - The Idiot ( 4.15 )
1870 - Complete Works ( 4.42 )
1871 - Through the Looking-Glass, and What Alice Found There (Alice's Adventures in Wonderland #2) ( 4.09 )
1872 - Middlemarch ( 3.89 )
1873 - Around the World in Eighty Days ( 3.87 )
1874 - The Complete Fairy Tales ( 4.27 )
1875 - Illuminations ( 4.42 )
1876 - The Adventures of Tom Sawyer ( 3.86 )
1877 - L'Assommoir (The Dram Shop) (The Dram Shop) (Les Rougon-Macquart, #7) ( 4.05 )
1878 - Human, All Too Human ( 4.2 )
1879 - Sir Gibbie ( 4.25 )
1880 - The Brothers Karamazov ( 4.28 )
1881 - The Prince and the Pauper ( 3.81 )
1882 - The Gay Science ( 4.23 )
1883 - Thus Spoke Zarathustra ( 4.03 )
1884 - The Death of Ivan Ilych ( 3.98 )
1885 - Germinal (Les Rougon-Macquart, #13) ( 4.05 )
1886 - Beyond Good and Evil ( 4.0 )
1887 - A Study in Scarlet (Sherlock Holmes, #1) ( 4.13 )
1888 - The Complete Fairy Tales ( 4.33 )
1889 - The Collected Poems ( 4.25 )
1890 - Hunger ( 4.11 )
1891 - A Scandal in Bohemia (The Adventures of Sherlock Holmes, #1) ( 4.22 )
1892 - The Adventures of Sherlock Holmes (Sherlock Holmes, #3) ( 4.27 )
1893 - The Memoirs of Sherlock Holmes (Sherlock Holmes, #4) ( 4.33 )
1894 - The Jungle Books ( 3.97 )
1895 - The Importance of Being Earnest and Other Plays ( 4.24 )
1896 - Story of a Soul ( 4.36 )
1897 - De Profundis and Other Writings ( 4.19 )
1898 - The War of the Worlds ( 3.75 )
1899 - The Complete Works of William Shakespeare ( 4.62 )
1900 - Selected Stories ( 4.35 )
1901 - The Tale of Peter Rabbit ( 4.14 )
1902 - Holy Bible ( 4.66 )
1903 - The Scarlet Pimpernel ( 4.05 )
1904 - The Return of Sherlock Holmes (Sherlock Holmes, #6) ( 4.27 )
1905 - A Little Princess ( 4.19 )
1906 - The Unabridged Devil's Dictionary ( 4.15 )
1907 - The Shepherd of the Hills ( 4.14 )
1908 - The Complete Anne of Green Gables Boxed Set (Anne of Green Gables, #1-8) ( 4.42 )
1909 - Martin Eden ( 4.31 )
1910 - Gitanjali ( 4.33 )
1911 - The Secret Garden ( 4.09 )
1912 - Daddy-Long-Legs (Daddy-Long-Legs, #1) ( 4.07 )
1913 - In the Shadow of Young Girls in Flower (In Search of Lost Time, #2) ( 4.39 )
1914 - Rashomon and Seventeen Other Stories ( 4.1 )
1915 - Jesus the Christ ( 4.66 )
1916 - The Mysterious Stranger ( 4.14 )
1917 - Anne's House of Dreams (Anne of Green Gables, #5) ( 4.1 )
1918 - The Elements of Style ( 4.17 )
1919 - Remembrance of Things Past ( 4.28 )
1920 - The Guermantes Way ( 4.33 )
1921 - Rilla of Ingleside (Anne of Green Gables, #8) ( 4.13 )
1922 - Remembrance of Things Past ( 4.53 )
1923 - Leave It to Psmith (Psmith, #4 ; Blandings Castle, #2) ( 4.28 )
1924 - The Complete Sherlock Holmes ( 4.49 )
1925 - The Captive & The Fugitive (In Search of Lost Time, #5-6) ( 4.41 )
1926 - The World of Winnie-the-Pooh ( 4.41 )
1927 - Time Regained (In Search of Lost Time, #7) ( 4.5 )
1928 - The House at Pooh Corner ( 4.35 )
1929 - Letters to a Young Poet ( 4.35 )
1930 - The Complete Sherlock Holmes, Volume II ( 4.44 )
1931 - The Joy of Cooking ( 4.15 )
1932 - Journey to the End of the Night ( 4.25 )
1933 - The Complete Novels ( 4.54 )
1934 - I, Claudius/Claudius the God ( 4.42 )
1935 - Musashi ( 4.41 )
1936 - Three Comrades ( 4.48 )
1937 - The Cost of Discipleship ( 4.35 )
1938 - The Science of Mind ( 4.39 )
1939 - Arch of Triumph ( 4.39 )
1940 - The Little Prince ( 4.23 )
1941 - Ø¹Ø¨ÙØ±ÙØ© Ø¹ÙØ± ( 4.25 )
1942 - The Little House ( 4.27 )
1943 - KÃ¼rk Mantolu Madonna ( 4.55 )
1944 - Ficciones ( 4.48 )
1945 - The Aleph and Other Stories ( 4.41 )
1946 - The Complete Stories ( 4.34 )
1947 - Survival in Auschwitz ( 4.32 )
1948 - King of the Wind ( 4.17 )
1949 - Paroles ( 4.27 )
1950 - à®ªà¯à®©à¯à®©à®¿à®¯à®¿à®©à¯ à®à¯à®²à¯à®µà®©à¯ [Ponniyin Selvan] ( 4.71 )
1951 - The Foundation Trilogy (Foundation, #1-3) ( 4.37 )
1952 - Holy Bible ( 4.55 )
1953 - The Flight of the Feathered Serpent ( 4.55 )
1954 - The Return of the King (The Lord of the Rings, #3) ( 4.48 )
1955 - Les rois maudits Vols 1-7 ( 4.44 )
1956 - Through Gates of Splendor ( 4.37 )
1957 - The Cairo Trilogy (The Cairo Trilogy #1-3) ( 4.46 )
1958 - Exodus ( 4.31 )
1959 - Life and Fate ( 4.44 )
1960 - The Annotated Alice ( 4.48 )
1961 - New World Translation of the Holy Scriptures ( 4.59 )
1962 - Labyrinths ( 4.47 )
1963 - The Civil War ( 4.58 )
1964 - The Feynman Lectures on Physics ( 4.57 )
1965 - Manchild in the Promised Land ( 4.3 )
1966 - The Disorderly Knights (The Lymond Chronicles, #3) ( 4.57 )
1967 - The Master and Margarita ( 4.33 )
1968 - The Proper Role of Government ( 4.49 )
1969 - Pawn in Frankincense (The Lymond Chronicles, #4) ( 4.64 )
1970 - The Fortress ( 4.67 )
1971 - Tutunamayanlar ( 4.61 )
1972 - Le Monogramme ( 4.78 )
1973 - J.R.R. Tolkien 4-Book Boxed Set ( 4.58 )
1974 - The Power Broker ( 4.51 )
1975 - Checkmate (The Lymond Chronicles, #6) ( 4.71 )
1976 - Roots ( 4.39 )
1977 - A Lover's Discourse ( 4.37 )
1978 - The Best of Roald Dahl ( 4.38 )
1979 - GÃ¶del, Escher, Bach ( 4.29 )
1980 - Cosmos ( 4.35 )
1981 - The Lord God Made Them All ( 4.36 )
1982 - The Book of Disquiet ( 4.52 )
1983 - Essays and Lectures ( 4.27 )
1984 - Ø§ÙØ¥Ø³ÙØ§Ù Ø¨ÙÙ Ø§ÙØ´Ø±Ù ÙØ§ÙØºØ±Ø¨ ( 4.46 )
1985 - Lonesome Dove ( 4.44 )
1986 - The Hitchhiker's Guide to the Galaxy ( 4.5 )
1987 - Calvin and Hobbes ( 4.61 )
1988 - The Essential Calvin and Hobbes ( 4.64 )
1989 - The Hobbit ( 4.48 )
1990 - The Authoritative Calvin And Hobbes ( 4.7 )
1991 - Rain of Gold ( 4.49 )
1992 - The Indispensable Calvin and Hobbes ( 4.71 )
1993 - Mark of the Lion Trilogy ( 4.75 )
1994 - The Complete Aubrey/Maturin Novels (5 Volumes) ( 4.69 )
1995 - The Calvin and Hobbes Tenth Anniversary Book ( 4.63 )
1996 - Calvin and Hobbes ( 4.75 )
1997 - The Song of the Lioness Quartet (Song of the Lioness, #1-4) ( 4.57 )
1998 - Harry Potter Boxset (Harry Potter, #1-7) ( 4.73 )
1999 - The Harry Potter Collection (Harry Potter, #1-4) ( 4.63 )
2000 - Standing for Something ( 4.64 )
2001 - A Storm of Swords (A Song of Ice and Fire, #3-1) ( 4.5 )
2002 - Way to Be! ( 4.62 )
2003 - The Complete Far Side, 1980-1994 ( 4.66 )
2004 - Ù¾ÛØ±Ù Ú©Ø§ÙÙ ( 4.58 )
2005 - The Complete Calvin and Hobbes ( 4.8 )
2006 - Warriors Boxed Set (Warriors, #1-3) ( 4.67 )
2007 - ESV Study Bible ( 4.76 )
2008 - The Absolute Sandman, Vol. 4 ( 4.75 )
2009 - Black Dagger Brotherhood ( 4.69 )
2010 - The Years Distilled ( 4.93 )
2011 - Family Secrets ( 5.0 )
2012 - A Book About Absolutely Nothing. ( 5.0 )
2013 - Blade Heart ( 4.93 )
2014 - An Elephant Is On My House ( 5.0 )

In [49]:
best_books = df.loc[df.groupby('year')['rating'].idxmax(), ['year', 'name', 'author', 'rating']]
best_books

      year                              name                      author  rating
1398 -1500             The Epic of Gilgamesh                   Anonymous    3.60
246   -800             The Iliad/The Odyssey                       Homer    4.01
1397  -560                    Aesop's Fables                       Aesop    4.03
674   -512                    The Art of War                     Sun_Tzu    3.92
746   -500                 The Bhagavad Gita                   Anonymous    4.06
...    ...                               ...                         ...     ...
2920  2010               The Years Distilled               Dennis_Sharpe    4.93
2909  2011                    Family Secrets              Rebekah_McClew    5.00
2145  2012  A Book About Absolutely Nothing.                  I_M_Nobody    5.00
3712  2013                       Blade Heart                 Chris_Lange    4.93
1718  2014        An Elephant Is On My House  Othen_Donald_Dale_Cummings    5.00

[293 rows x 4 columns]